### ISSUE TITLE
'/redfish/v1/Systems/1/Actions/ComputerSystem.Reset' doesn't exist

### ISSUE THREAD

**Issue by nicwu-cel** [opencomputeproject/HWMgmt-DeviceMgr-PSME#2]
As https://github.com/opencomputeproject/HWMgmt-DeviceMgr-PSME/tree/main/PSME/PSME_REDFISH_API says, we could reboot device through PSME. However, there's no "/redfish/v1/Systems" on my side as below. Could we enable it with configuration file? 

```
{
   "Managers" : {
      "@odata.id" : "/redfish/v1/Managers"
   },
   "@odata.id" : "/redfish/v1",
   "Id" : "RootService",
   "RedfishVersion" : "1.0.2",
   "@odata.type" : "#ServiceRoot.v1_1_1.ServiceRoot",
   "Links" : {
      "Sessions" : {
         "@odata.id" : "/redfish/v1/SessionService/Sessions"
      }
   },
   "Description" : "Service Root description",
   "UUID" : "439bc0ea-28bd-11ed-958d-87a576307be4",
   "AccountService" : {
      "@odata.id" : "/redfish/v1/AccountService"
   },
   "Chassis" : {
      "@odata.id" : "/redfish/v1/Chassis"
   },
   "Name" : "PSME Service Root",
   "@odata.context" : "/redfish/v1/$metadata#ServiceRoot.ServiceRoot",
   "SessionService" : {
      "@odata.id" : "/redfish/v1/SessionService"
   }
}
```

**Comment by jcleung5549** [comment]
I asked the original RSD-PSME developers for their take on this issue. Their response was "In RSD-PSME, the Network agent did not expose a System resource at all. So, assuming that this person is modifying the network agent, this wouldn’t be a surprise."

**Comment by nicwu-cel** [comment]
I notice that there's a URL /redfish/v1/Chassis/1/Actions/Chassis.Reset which offers below 4 types 
"ForceOff",
"GracefulShutdown",
"GracefulRestart",
"ForceRestart"
to perform system power management.

 I noticed that GracefulShutdown" and "GracefulRestart" are supported through "shutdown -h" and "shutdown -r" under /usr/local/bin/psme.sh but "ForceOff" and "ForceRestart" are not supported.

"ForceOff" and "ForceRestart" may should supported by the platform vendor in specific HW platform, right?
That means we could add some changes to support these 2 types in our platform.

**Comment by jcleung5549** [comment]
OCP prescribes what manageability should be supported via the OCP profiles - https://github.com/opencomputeproject/HWMgmt-OCP-Profiles.  Currently, only the profiles for HW Baseline and Server have been proposed and approved.  The HW Baseline profile prescribes common manageability across the OCP platform types.  The Server profile extends the HW Baseline and adds more support requirements.  The networking platform have made no proposal for extension, so it is a open field for an OCP Profile to Networking Platforms.

The HW Baseline Profile requires that "ForceRestart" be supported.  The Server Profile extends the requirement to "ForceOff", "On", "ForceRestart". 

"ForceRestart" should be supported to conform to the HW Baseline Profile.  If you believe "ForceOff" should be support on networking platforms, please submit an issue in the OCP Profile repository.  Then I can make sure a Network Device Profile exists as the context for approving the your changes.

**Comment by nicwu-cel** [comment]
Therefore, it is acceptable to add "ForceRestart" support in PSME code based on the HW baseline, and "ForceOff" should first be confirmed with OCP Profile whether it should be applied to the networking platform, right?

**Comment by jcleung5549** [comment]
Absolutely.
